export const productData = [
  {
    "id":495,
    "brand":"maybelline",
    "name":"Maybelline Face Studio Master Hi-Light Light Booster Bronzer",
    "price":"14.9",
    "image_link":"/imagesSource/495.png",
    "description":"Maybelline Face Studio Master Hi-Light Light Boosting bronzer formula has an expert \nbalance of shade + shimmer illuminator for natural glow. Skin goes \nsoft-lit with zero glitz.\n\n\t\tFor Best Results: Brush over all shades in palette and gently sweep over \ncheekbones, brow bones, and temples, or anywhere light naturally touches\n the face.\n\n\t\t\n\t\n\n                    ",
    "rating":5.0,
    "category":"powder",
    "product_type":"bronzer",
  },
  {
    "id":488,
    "brand":"maybelline",
    "name":"Maybelline Fit Me Bronzer",
    "price":"10.2",
    "image_link":"/imagesSource/488.png",
    "description":"Why You'll Love It\n\nLightweight pigments blend easily and wear evenly\nProvides a natural, fade-proof bronzed color that leaves skin the way it was meant to be...fresh, breathing and natural\n\nFor Best Results: For soft, natural look, brush along cheekbone, sweeping upward.",
    "rating":4.5,
    "category":"cream",
    "product_type":"bronzer",
  },
  {
  "id":477,
    "brand":"maybelline",
    "name":"Maybelline Facestudio Master Contour Kit",
    "price":"15.9",
    "image_link":"/imagesSource/477.png",
    "description":"Maybelline Facestudio Master Contour Kit is the ultimate on the go all-in-one palette, with contouring brush included.  Define and highlight in a New York minute with this effortless 3-step face contouring kit.  This easy-to-use 3-step face contouring kit features a bronzer, blush and highlighter.",
    "rating":4.0,
    "category":"powder",
    "product_type":"bronzer",
  },
  {
    "id":468,
    "brand":"maybelline",
    "name":"Maybelline Face Studio Master Hi-Light Light Booster Blush",
    "price":"14.9",
    "image_link":"/imagesSource/468.png",
    "description":"Maybelline Face Studio Master Hi-Light Light Boosting blush formula has an expert \nbalance of shade + shimmer illuminator for natural glow. Skin goes \nsoft-lit with zero glitz.\n\n\t\tFor Best Results: Brush over all shades in palette and gently sweep over \ncheekbones, brow bones, and temples, or anywhere light naturally touches\n the face.\n\n\t\t\n\t\n\n                    ",
    "rating":5.0,
    "category":"powder",
    "product_type":"blush",
  },
  {
    "id":452,
    "brand":"maybelline",
    "name":"Maybelline Face Studio Master Hi-Light Light Booster Blush ",
    "price":"14.9",
    "image_link":"/imagesSource/452.png",
    "description":"Maybelline Face Studio Master Hi-Light Light Boosting blush formula has an expert \nbalance of shade + shimmer illuminator for natural glow. Skin goes \nsoft-lit with zero glitz.\n\n\t\tFor Best Results: Brush over all shades in palette and gently sweep over \ncheekbones, brow bones, and temples, or anywhere light naturally touches\n the face.\n\n\t\t\n\t\n\n                    ",
    "rating":5.0,
    "category":"powder",
    "product_type":"blush",
  },
  {
    "id":439,
    "brand":"maybelline",
    "name":"Maybelline Fit Me Blush",
    "price":"10.2",
    "image_link":"/imagesSource/439.png",
    "description":"Maybelline Fit Me Blush has lightweight pigments blend easily and wear evenly. It provides a natural, fade-proof cheek color that leaves skin the way it was meant to be...fresh, breathing, and natural.\n\nFor Best Results: For soft, natural look, brush along cheekbone, sweeping upward.",
    "rating":4.5,
    "category":"powder",
    "product_type":"blush",
  },
  {
    "id":414,
    "brand":"maybelline",
    "name":"Maybelline Dream Bouncy Blush",
    "price":"11.9",
    "image_link":"/imagesSource/414.png",
    "description":"Now, blush has bounce! Freshest flush ever:• New bouncy texture is formulated with silicone elastomers• Lightweight like a powder, yet melts seamlessly into skin like a cream giving you a fresh flush• Dermatologist tested• Allergy tested• Non-comedogenic\n                    \n                    \n                    \n                        \n                        For best results: With your fingertips, blend a small amount of\n blush onto the apples of your cheeks, applying from your cheekbones to \nyour temples. To build colour intensity, apply more blush. \n                    ",
    "rating":4.5,
    "category":"cream",
    "product_type":"blush",
  },
  {
    "id":398,
    "brand":"maybelline",
    "name":"Maybelline Color Sensational Lipliner",
    "price":"18.2",
    "image_link":"/imagesSource/398.png",
    "description":"Keep your Maybelline lip color beautiful with matching lip liners that won't smudge, smear or bleed for smooth, defined lips. For best results: Line your lips starting in the center of your upper lip. Work from the \ncenter to outer edges of your lips using small strokes, following the \ncontour of your mouth. Follow the same technique for your bottom lip. To\n extend the wear of your favorite lip color or lip gloss, first fill in \nyour lips completely with lip liner. ",
    "rating":3.5,
    "category":"lipstick",
    "product_type":"lip_liner",
  },
]
